module:
  addtoany: 0
  aggregator: 0
  automated_cron: 0
  backup_migrate: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_templates: 0
  ckeditor_templates_ui: 0
  ckeditor_youtube: 0
  ckwordcount: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  content_moderation: 0
  content_moderation_notifications: 0
  contextual: 0
  css_editor: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  customiepl_socialsso: 0
  datetime: 0
  dblog: 0
  devel: 0
  domain: 0
  domain_access: 0
  domain_alias: 0
  domain_config: 0
  domain_source: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  imce: 0
  kint: 0
  layout_discovery: 0
  link: 0
  linkit: 0
  media: 0
  menu_ui: 0
  message: 0
  message_notify: 0
  metatag: 0
  metatag_app_links: 0
  metatag_dc: 0
  metatag_dc_advanced: 0
  metatag_facebook: 0
  metatag_google_plus: 0
  metatag_hreflang: 0
  metatag_open_graph: 0
  metatag_open_graph_products: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  module_builder: 0
  nocurrent_pass: 0
  node: 0
  notification: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panelizer: 0
  panelizer_quickedit: 0
  panels: 0
  panels_ipe: 0
  path: 0
  popular_tags: 0
  private_message: 0
  quickedit: 0
  rdf: 0
  redirect_after_login: 0
  remove_generator: 0
  responsive_image: 0
  robotstxt: 0
  search: 0
  seckit: 0
  shortcut: 0
  simple_adsense: 0
  simplelogin: 0
  smtp: 0
  social_api: 0
  social_auth: 0
  social_auth_facebook: 0
  social_auth_google: 0
  social_auth_linkedin: 0
  social_auth_slack: 0
  statistics: 0
  syslog: 0
  system: 0
  taxonomy: 0
  term_reference_fancytree: 0
  text: 0
  token: 0
  toolbar: 0
  total_control: 0
  tour: 0
  tracker: 0
  update: 0
  url_redirect: 0
  user: 0
  video_embed_field: 0
  video_embed_wysiwyg: 0
  views_ui: 0
  visitors: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
  vartheme_admin: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
