toolbar_items:
  - devel.cache_clear
  - devel.admin_settings_link
  - devel.layout_info
  - devel.menu_rebuild
  - devel.run_cron
  - devel.theme_registry
  - devel.session
_core:
  default_config_hash: IQjf_ytthngZTAk_MU8-74VecArWD3G5g0oEH6PM6GA
