smtp_on: true
smtp_host: mail.tell.com
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: standard
smtp_username: alyza.cruz@tell.com
smtp_password: phiMEq52ijan
smtp_from: alyza.cruz@tell.com
smtp_fromname: 'Alyza Cruz'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
