features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
custom_css: 0
disable_google_fonts: 0
css_enabled: 1
css: ".popular-tags .tag-terms a {\r\n  padding: 5px;\r\n    background-color: #ccc;\r\n    border-radius: 5px;\r\n}\r\n.ipe-categories .ipe-category[data-category=\"Custom\"],.ipe-categories .ipe-category[data-category=\"Chaos Tools\"] ,\r\n.ipe-categories .ipe-category[data-category=\"Dashboard\"] ,\r\n.ipe-categories .ipe-category[data-category=\"Devel\"] ,\r\n.ipe-categories .ipe-category[data-category=\"Help\"] ,\r\n.ipe-categories .ipe-category[data-category=\"Social Auth\"] \r\n.ipe-categories .ipe-category[data-category=\"System\"],\r\n.ipe-categories .ipe-category[data-category=\"Menus\"] , \r\n.ipe-categories .ipe-category[data-category=\"Social Auth\"] ,\r\n.ipe-categories .ipe-category[data-category=\"core\"] \r\n{\r\n    display: none;\r\n}"
plaintext_enabled: 0
autopreview_enabled: 0
preview_path: ''
