<?php
  function private_message_adjust_theme($existing, $type, $theme, $path){

    return array(
      'private_message_adjust' => array(
        'variable' => array('items' => array(), 'title' => '')
      )
    );
  }

  function private_message_adjust_page_attachments(array &$attachments){
    $attachments['#attached']['library'][] = 'private_message_adjust/private_message_adjust';
  }

  function private_message_adjust_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
    if ($form_id == 'private_message_add_form'){
      // echo "<pre>";
      // var_dump($form);
      // echo "</pre>";
      // exit();
    }

  }