<?php

/**
 * Implements hook_form_alter().
 *
 * Adds custom cron url to existing form
 */
function data_migration_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if($form_id === 'system_cron_settings') {
    $cronUrl = $form['cron_url']['#markup'];
    $url = buildUrl();
    $element = t('To run data migration cron, go to <a href=":cron" class="system-cron-settings__link">@cron</a>', [':cron' => $url, '@cron' => $url]);
    $dataMigrationUrl = '<p>' . $element . '</p>';
    $form['cron_url']['#markup'] = $cronUrl . $dataMigrationUrl;
  }
}

/**
 * Builds data migration cron url
 * @return string
 */
function buildUrl() {
  $key = \Drupal::state()->get('system.cron_key');
  $host = \Drupal::request()->getSchemeAndHttpHost();
  $path = \Drupal::service('path.current')->getPath();
  return $host . $path . '/data_migration/' . $key;
}
